name: agro_assist
description: Farmer-facing irrigation helper app (Flutter + FastAPI)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI & fonts
  google_fonts: ^6.2.1
  # Localization (built-in Flutter localizations)
  flutter_localizations:
    sdk: flutter
  # HTTP for later API calls
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # add your logo here (512x512 recommended)

# App icon config (uses assets/logo.png)
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/logo.png
  adaptive_icon_background: "#F9F871"   # soft yellow
  adaptive_icon_foreground: assets/logo.png
  remove_alpha_ios: true

# Splash screen config (uses same logo)
flutter_native_splash:
  color: "#EAFCD7"       # pale green
  image: assets/logo.png
  android: true
  ios: false
  android_12:
    color: "#EAFCD7"
    image: assets/logo.png
